FROM	ubuntu:20.04

LABEL	maintainer <aophion@student.21-school.ru>

RUN	apt-get update -y && \
	apt-get upgrade -y && \
	apt-get install -y \
	build-essential \
	python3.8 \
	vim \
	git

ENTRYPOINT	/bin/bash
